name: Python CI

on:
  push:
    branches: [ main ] # Or any other branches you want to trigger the workflow on
  pull_request:
    branches: [ main ] # Or any other branches you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest # You can choose other runners like windows-latest or macos-latest

    steps:
    - uses: actions/checkout@v4 # Checks out your repository under $GITHUB_WORKSPACE

    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13' # Specify Python 3.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Python script
      run: python main.py # Replace 'your_script_name.py' with the actual name of your Python file
